# Generated by Django 4.2.10 on 2024-02-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inalguração', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('endereço', models.CharField(max_length=50)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nome', models.CharField(max_length=50)),
                ('data_lançamento', models.DateField()),
                ('edicao', models.PositiveIntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fk_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.autor')),
                ('fk_editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.editora')),
            ],
        ),
    ]
