# Generated by Django 4.2.10 on 2024-02-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='edicao',
        ),
    ]
