# Generated by Django 4.2.10 on 2024-02-23 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_livro_edicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='use_fk',
            new_name='user_fk',
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao', models.IntegerField()),
                ('livro_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.livro')),
            ],
        ),
    ]
