# Generated by Django 4.2.10 on 2024-02-23 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='fk_autor',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=200)),
                ('descricao_pedido', models.TextField()),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='genero_fk',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.genero'),
        ),
        migrations.AddField(
            model_name='livro',
            name='fk_autor',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.autor'),
        ),
    ]
