# Generated by Django 4.2.10 on 2024-02-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_genero_livro_tipo_remove_livro_fk_autor_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='fk_autor',
            field=models.ManyToManyField(to='accounts.autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero_fk',
            field=models.ManyToManyField(to='accounts.genero'),
        ),
    ]
