# Generated by Django 4.2.10 on 2024-03-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_livro_fk_autor_alter_livro_genero_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='alugado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estoque',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
