# Generated by Django 4.2.10 on 2024-03-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_estoque_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_alugada',
            field=models.DateField(),
        ),
    ]
